In [224]:
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

In [283]:
pitchers_df = pd.read_csv('Data/pitchers_complete.csv')

In [269]:
pitchers_df.shape

(9655, 23)

In [284]:
data = pitchers_df.drop(['inducted', 'playerID', 'nameFirst', 'nameLast', 
                         'finalGame','bats', 'throws','weight', 'height','yearid'], axis=1)
data.fillna(0, inplace=True)
data['Batters_Faced']=pd.to_numeric(data['Batters_Faced'])
data.head()

Seasons  Wins  Loses  Games  Games_Started  Complete_Games  Shut_Outs  \
0        9    16     18    331              0               0          0   
1       13    66     60    448             91              22          5   
2        9     8     27    363              6               0          0   
3        6    22     40     79             65              52          0   
4        1     0      0      1              0               0          0   

   Earned_Runs  Strike_Outs  Walks  Games_Finished  Runs_Allowed  \
0          160          340    183             141           169   
1          468          641    457             235           503   
2          129          271    113              96           137   
3          285          161    192              14           442   
4            1            0      0               1             3   

   Batters_Faced  
0         1475.0  
1         4730.0  
2         1350.0  
3         2568.0  
4           12.0

In [285]:
target = pitchers_df['inducted']
target.fillna('N', inplace=True)
target_encoded = pd.get_dummies(target)
target_names = ['N', 'Y']
target_encoded.head()

N  Y
0  1  0
1  1  0
2  1  0
3  1  0
4  1  0

In [286]:
feature_names = data.columns
feature_names

Index(['Seasons', 'Wins', 'Loses', 'Games', 'Games_Started', 'Complete_Games',
       'Shut_Outs', 'Earned_Runs', 'Strike_Outs', 'Walks', 'Games_Finished',
       'Runs_Allowed', 'Batters_Faced'],
      dtype='object')

In [287]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(data, target_encoded, random_state=42)


In [306]:
from sklearn.preprocessing import StandardScaler
X_scaler = StandardScaler().fit(X_train)
y_scaler = StandardScaler().fit(y_train)
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)


/Users/chris.marchetti/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/chris.marchetti/anaconda3/lib/python3.7/site-packages/sklearn/preprocessing/data.py:645: DataConversionWarning: Data with input dtype uint8 were all converted to float64 by StandardScaler.
  return self.partial_fit(X, y)
/Users/chris.marchetti/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:4: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  after removing the cwd from sys.path.
/Users/chris.marchetti/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:5: DataConversionWarning: Data with input dtype int64, float64 were all converted to float64 by StandardScaler.
  """


array([[-0.817777  , -0.51636531, -0.52100314, ..., -0.46600958,
        -0.57332021, -0.55179375],
       [-0.60428107, -0.51636531, -0.57452711, ..., -0.45093645,
        -0.5644233 , -0.56231017],
       [-0.817777  , -0.51636531, -0.6012891 , ..., -0.46600958,
        -0.59704529, -0.57621897],
       ...,
       [-0.817777  , -0.51636531, -0.6012891 , ..., -0.45093645,
        -0.58518275, -0.57248734],
       [ 0.03620674, -0.01189125,  0.33538043, ..., -0.45093645,
         0.19774491,  0.08563659],
       [-0.60428107, -0.49343467, -0.54776513, ..., -0.40571708,
        -0.57332021, -0.54670517]])

In [289]:
rf = RandomForestClassifier(n_estimators=200)
rf = rf.fit(X_train_scaled, y_train)
rf.score(X_test_scaled, y_test)


0.992129246064623

In [291]:
rf.score(X_train_scaled,y_train)

0.9997237950559315

In [292]:
rf.predict(X_test_scaled)

array([[1., 0.],
       [1., 0.],
       [1., 0.],
       ...,
       [1., 0.],
       [1., 0.],
       [1., 0.]])

In [293]:
cnt = 0
for result in rf.predict(X_test_scaled):
    if result[1] == 1:
        cnt+=1
print(cnt)

15


In [294]:
count = 0
for result in rf.predict(X_train_scaled):
    if result[1] == 1:
        count+=1
print(count)

66


In [295]:
c = 0
for result in pitchers_df['inducted']:
    if result == 'Y':
        c+=1
print(c)

96


In [296]:
(count+cnt)/c

0.84375

In [247]:
predict_list= [predictions[1] for row in predictions]

In [249]:
predictions = rf.predict(X_test)
predict_vs_actual = {
    'predicted': predict_list,
    'actual': y_test['Y'],
    'check': y_test['Y']==predict_list}
# pd.DataFrame(predict_vs_actual)
predict_vs_actual

{'predicted': [array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),
  array([1., 0.]),

In [297]:
from sklearn.metrics import classification_report
predictions = rf.predict(X_test_scaled)
print(classification_report(y_test, predictions,
                            target_names=target_names))

              precision    recall  f1-score   support

           N       0.99      1.00      1.00      2386
           Y       0.80      0.43      0.56        28

   micro avg       0.99      0.99      0.99      2414
   macro avg       0.90      0.71      0.78      2414
weighted avg       0.99      0.99      0.99      2414
 samples avg       0.99      0.99      0.99      2414



In [298]:
rf.feature_importances_

array([0.04758928, 0.13737289, 0.04520753, 0.05294388, 0.06688864,
       0.05923218, 0.11171557, 0.05994708, 0.07964091, 0.0586829 ,
       0.05991239, 0.07374527, 0.14712149])

In [299]:
pitchers_df[pitchers_df['inducted']=='Y']

playerID nameFirst   nameLast  Seasons  Wins  Loses  Games  \
95    alexape01      Pete  Alexander       21   373    208    696   
188   ansonca01       Cap      Anson        2     0      1      3   
513   becklja01      Jake    Beckley        1     0      1      1   
570   bendech01     Chief     Bender       16   212    127    459   
740   blylebe01      Bert   Blyleven       24   287    250    692   
757   boggswa01      Wade      Boggs        2     0      0      2   
938   bresnro01     Roger  Bresnahan        3     4      1      9   
997   broutda01       Dan  Brouthers        2     0      2      4   
1034  brownmo01  Mordecai      Brown       15   239    130    481   
1106  bunniji01       Jim    Bunning       18   224    184    591   
1128  burkeje01     Jesse    Burkett        3     3     11     23   
1311  carltst01     Steve    Carlton       27   329    244    741   
1476  chesbja01      Jack    Chesbro       12   198    132    392   
1540  clarkjo01      John   Clarkson       13   328    178    531   
1594   cobbty01        Ty       Cobb        2     0      0      3   
1788  covelst01      Stan  Coveleski       14   215    142    450   
2003  davisge01    George      Davis        1     0      1      3   
2039   deandi01     Dizzy       Dean       12   150     83    317   
2319  drysddo01       Don   Drysdale       14   209    166    518   
2418  eckerde01    Dennis  Eckersley       25   197    171   1071   
2574  ewingbu01      Buck      Ewing        6     2      3      9   
2579  faberre01       Red      Faber       20   254    213    669   
2638  fellebo01       Bob     Feller       18   266    162    570   
2702  fingero01    Rollie    Fingers       17   114    118    944   
2809   fordwh01    Whitey       Ford       16   236    106    498   
2851   foxxji01    Jimmie       Foxx        2     1      0     10   
2984  galvipu01       Pud     Galvin       17   365    310    705   
3125  gibsobo01       Bob     Gibson       17   251    174    528   
3182  glavito02       Tom    Glavine       22   305    203    682   
3224  gomezle01     Lefty      Gomez       14   189    102    368   
...         ...       ...        ...      ...   ...    ...    ...   
6777  perryga01   Gaylord      Perry       25   314    265    777   
6905  planked01     Eddie      Plank       17   326    194    623   
7061  radboch01  Old Hoss   Radbourn       11   310    194    527   
7254   ricesa01       Sam       Rice        2     1      1      9   
7324  rixeyep01      Eppa      Rixey       21   266    251    692   
7354  roberro01     Robin    Roberts       21   286    245    676   
7537  ruffire01       Red    Ruffing       23   273    225    624   
7550  rusieam01      Amos      Rusie       10   246    174    463   
7565   ruthba01      Babe       Ruth       10    94     46    163   
7578   ryanno01     Nolan       Ryan       27   324    292    807   
7834  seaveto01       Tom     Seaver       22   311    205    656   
8015  sislege01    George     Sisler        7     5      6     24   
8136  smoltjo01      John     Smoltz       22   213    155    723   
8189  spahnwa01    Warren      Spahn       22   363    245    750   
8199  speaktr01      Tris    Speaker        1     0      0      1   
8467  suttebr01     Bruce     Sutter       12    68     71    661   
8469  suttodo01       Don     Sutton       25   324    256    774   
8877  vanceda01     Dazzy      Vance       18   197    140    442   
8997  wadderu01      Rube    Waddell       14   193    143    407   
9010  wagneho01     Honus     Wagner        2     0      0      2   
9049  wallabo01     Bobby    Wallace        4    24     22     57   
9067  walshed01        Ed      Walsh       14   195    126    430   
9089   wardjo01      John       Ward        7   164    103    293   
9179  welchmi01    Mickey      Welch       13   307    210    565   
9245  whitede01    Deacon      White        2     0      0      2   
9300  wilheho01      Hoyt    Wilhelm       26   143    122   1070   
9359 

In [304]:
X_scaler.transform(data.iloc[95].array.reshape(1,-1))

AttributeError: 'PandasArray' object has no attribute 'reshape'